name: Backup DB (manual)
on:
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Dump database (custom format)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          TS=$(date +%Y%m%d%H%M%S)
          pg_dump "$DATABASE_URL" --no-owner --format=custom --file "backup_${TS}.dump"
          echo "Created backup_${TS}.dump"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: "*.dump"
          if-no-files-found: error