name: DB auto deploy

on:
  push:
    branches: [main]
    paths:
      - "supabase/migrations/**.sql"   # only when migrations change

permissions:
  contents: read

concurrency:
  group: db-deploy
  cancel-in-progress: true

jobs:
  deploy:
    # one-line kill switch in commit message
    if: ${{ !contains(github.event.head_commit.message, '[skip-db-deploy]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_TELEMETRY_DISABLED: 1
        run: |
          if [[ -z "$DATABASE_URL" ]]; then echo "❌ DATABASE_URL missing"; exit 1; fi
          supabase --version
          echo "➡️  Applying pending migrations to remote DB..."
          supabase db push --db-url "$DATABASE_URL"

  smoke:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: DB smoke test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [[ -z "$DATABASE_URL" ]]; then echo "❌ DATABASE_URL missing"; exit 1; fi
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/qa/smoke.sql