name: Deploy migrations
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy from
        default: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Guard main branch
        run: |
          if [[ "${{ inputs.ref }}" != "main" ]]; then
            echo "Error: Deploy only from main branch."
            exit 1
          fi
      - name: Apply migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [[ -z "${DATABASE_URL}" ]]; then
            echo "Error: Missing DATABASE_URL secret."
            exit 1
          fi
          supabase db reset --db-url "$DATABASE_URL" --force --no-seed --use-mig-dir supabase/migrations
          echo "✅ Migrations applied."