name: DB smoke
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Run smoke SQL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [[ -z "$DATABASE_URL" ]]; then echo "DATABASE_URL missing"; exit 1; fi
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/qa/smoke.sql