name: Deploy Supabase Migrations
on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - uses: supabase/setup-cli@v1

      - name: Clean prepared statements and deploy schema
        run: |
          # Clean any prepared statements
          psql "$DATABASE_URL" -c "DEALLOCATE ALL;"
          
          # Deploy schema with force to bypass migration version conflicts
          # This ensures the database schema matches our single migration file exactly
          echo "Deploying schema with force to resolve migration version conflicts..."
          echo "Current migration file: $(ls supabase/migrations/)"
          supabase db push --db-url "$DATABASE_URL" --debug --force
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}