name: Deploy Supabase Schema

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "supabase/**.sql"
      - ".github/workflows/deploy-migrations.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Connectivity probe
        run: |
          set -e
          psql "$DATABASE_URL" -Atqc "select 'DB reachable' as ok, current_user, current_date;"

      - name: Ensure required extensions
        run: |
          set -e
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c 'create extension if not exists "pgcrypto";'

      - name: Apply schema
        run: |
          set -e
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/schema_inferred.sql