name: Deploy Database Migrations

on:
  workflow_dispatch:  # manual-only for now

permissions:
  contents: read

concurrency:
  group: supabase-migrations
  cancel-in-progress: true

jobs:
  deploy:
    name: Apply Supabase migrations
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify Supabase CLI (no global install)
        run: npx supabase --version

      - name: Apply migrations
        run: |
          set -euo pipefail
          echo "Starting Supabase migrations…"
          npx supabase db push
          echo "Automation Verified ✅ — migrations applied successfully"