name: Deploy Supabase Schema (Session Pooler)

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**/*.sql"
      - "supabase/migrations/*.sql"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Connectivity probe (Session Pooler)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Expecting an IPv4-friendly pooler URL, e.g.:
          # postgresql://user:pass@aws-0-<region>.pooler.supabase.com:6543/postgres?sslmode=require
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c 'select version();'

      - name: Apply migrations (sorted by timestamp)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          shopt -s nullglob
          mapfile -t files < <(printf '%s\n' supabase/migrations/*.sql supabase/migrations/**/*.sql | sort)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No migration files found. Skipping."
            exit 0
          fi
          for file in "${files[@]}"; do
            echo "Applying $file"
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$file"
          done
          echo "Automation Verified ✅ — migrations applied via Session Pooler"

