name: Deploy Supabase Migrations

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - uses: supabase/setup-cli@v1

      - name: Validate migration files
        run: |
          echo "Migration files in supabase/migrations:"
          ls -la supabase/migrations/ || echo "No migration files found"
          echo "Count: $(ls -1 supabase/migrations/*.sql 2>/dev/null | wc -l)"

      - name: Deploy migrations
        run: |
          echo "Deploying migrations incrementally..."
          supabase migration deploy --debug
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Verify deployment
        run: |
          echo "Listing applied migrations from database..."
          psql "$DATABASE_URL" -c "SELECT * FROM supabase_migrations.schema_migrations ORDER BY version;"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
