name: Detect DB changes
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: db-detect-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run detector
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: node scripts/db-change-detect.mjs