name: Detect DB changes
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: node scripts/db-change-detect.mjs