name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    if: ${{ false }}   # TEMP: fully disabled to unblock merges
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}