name: PR DB OK comment
on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  issues: write
jobs:
  apply-label:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/db-ok') &&
      (github.event.comment.author_association == 'MEMBER' ||
       github.event.comment.author_association == 'OWNER'  ||
       github.event.comment.author_association == 'COLLABORATOR')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const issue_number = context.payload.issue.number;
            await github.rest.issues.addLabels({owner, repo, issue_number, labels: ['db-migrations-ok']});